# Generated by Django 2.2.6 on 2019-10-17 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='C人员表',
            fields=[
                ('m标识', models.AutoField(primary_key=True, serialize=False)),
                ('m姓名', models.CharField(max_length=20)),
                ('m单位', models.CharField(max_length=20)),
                ('m职务', models.CharField(max_length=10)),
                ('m电话', models.CharField(max_length=20)),
                ('m邮箱', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='C文档表',
            fields=[
                ('m标识', models.AutoField(primary_key=True, serialize=False)),
                ('m名称', models.CharField(max_length=20)),
                ('m标题', models.CharField(max_length=50)),
                ('m摘要', models.CharField(max_length=100)),
                ('m创建者', models.IntegerField()),
                ('m创建时间', models.TimeField(auto_now_add=True)),
                ('m修改者', models.IntegerField()),
                ('m修改号', models.IntegerField()),
                ('m修改时间', models.TimeField(auto_now=True)),
                ('m内容', models.TextField()),
            ],
        ),
    ]
