# Generated by Django 2.2.6 on 2019-10-27 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('知识库', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='c文档表',
            name='mi目录显示',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='c文档表',
            name='m上级文档',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='c文档表',
            name='m排列位置',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='c文档表',
            name='m修改者',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='c文档表',
            name='m创建者',
            field=models.IntegerField(default=0),
        ),
    ]
