# Generated by Django 2.2.6 on 2019-10-27 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('知识库', '0002_auto_20191027_2035'),
    ]

    operations = [
        migrations.AlterField(
            model_name='c文档表',
            name='m修改号',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='c文档表',
            name='m排列位置',
            field=models.IntegerField(default=99999999),
        ),
        migrations.AlterField(
            model_name='c文档表',
            name='m摘要',
            field=models.CharField(default='(没有描述)', max_length=100),
        ),
    ]
