# Generated by Django 2.2.6 on 2019-11-01 02:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('知识库', '0003_auto_20191027_2056'),
    ]

    operations = [
        migrations.AlterField(
            model_name='c文档表',
            name='m上级文档',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='知识库.C文档表'),
        ),
        migrations.AlterField(
            model_name='c文档表',
            name='m排列位置',
            field=models.IntegerField(default=9999),
        ),
    ]
