# Generated by Django 2.2.6 on 2019-11-21 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('知识库', '0004_auto_20191101_1006'),
    ]

    operations = [
        migrations.CreateModel(
            name='C图片表',
            fields=[
                ('m标识', models.AutoField(primary_key=True, serialize=False)),
                ('m名称', models.CharField(max_length=20)),
                ('m标题', models.CharField(max_length=50)),
                ('m图片', models.ImageField(upload_to='知识库')),
            ],
        ),
        migrations.CreateModel(
            name='C文件表',
            fields=[
                ('m标识', models.AutoField(primary_key=True, serialize=False)),
                ('m名称', models.CharField(max_length=20)),
                ('m标题', models.CharField(max_length=50)),
                ('m文件', models.FileField(upload_to='知识库')),
            ],
        ),
    ]
