# Generated by Django 4.0.5 on 2022-06-09 08:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('知识库', '0005_c图片表_c文件表'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='c文档表',
            name='m内容',
        ),
    ]
